source "https://api.berkshelf.com"

metadata

cookbook "apt"
cookbook "ark"
cookbook "bluepill"
cookbook "build-essential"
cookbook "java"
cookbook "monit"
cookbook "nginx"
cookbook "ohai"
cookbook "python"
cookbook "rsyslog"
cookbook "windows"
cookbook "yum"
cookbook "yum-epel"

cookbook 'elasticsearch', git: 'git://github.com/elasticsearch/cookbook-elasticsearch.git'




